<?xml version="1.0" encoding="utf-8"?><Database Name="BoxManagerDB" Class="BoxDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=BoxManagerDB;Integrated Security=True" SettingsObjectName="BoxManager.Properties.Settings" SettingsPropertyName="BoxManagerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Acciones" Member="Acciones">
    <Type Name="Accione">
      <Column Name="Id_Accion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Boxeadores" Member="Boxeadores">
    <Type Name="Boxeadore">
      <Column Name="Id_Boxeador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Rama" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Division" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Municipio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="Id_Categoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Rama" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Divisiones" Member="Divisiones">
    <Type Name="Divisione">
      <Column Name="Id_Division" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Municipios" Member="Municipios">
    <Type Name="Municipio">
      <Column Name="Id_Municipio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Registros" Member="Registros">
    <Type Name="Registro">
      <Column Name="Id_Registros" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Registro" Member="Registro1" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.accionesPor2Fechas" Method="accionesPor2Fechas">
    <Parameter Name="fecha1" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fecha2" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="accionesPor2FechasResult">
      <Column Name="Descripción" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>