#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxManager.Classes
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BoxManagerDB")]
	public partial class BoxDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccione(Accione instance);
    partial void UpdateAccione(Accione instance);
    partial void DeleteAccione(Accione instance);
    partial void InsertBoxeadore(Boxeadore instance);
    partial void UpdateBoxeadore(Boxeadore instance);
    partial void DeleteBoxeadore(Boxeadore instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertDivisione(Divisione instance);
    partial void UpdateDivisione(Divisione instance);
    partial void DeleteDivisione(Divisione instance);
    partial void InsertMunicipio(Municipio instance);
    partial void UpdateMunicipio(Municipio instance);
    partial void DeleteMunicipio(Municipio instance);
    partial void InsertRegistro(Registro instance);
    partial void UpdateRegistro(Registro instance);
    partial void DeleteRegistro(Registro instance);
    partial void InsertTorneo(Torneo instance);
    partial void UpdateTorneo(Torneo instance);
    partial void DeleteTorneo(Torneo instance);
    partial void InsertPelea(Pelea instance);
    partial void UpdatePelea(Pelea instance);
    partial void DeletePelea(Pelea instance);
    #endregion
		
		public BoxDBDataContext() : 
				base(global::BoxManager.Properties.Settings.Default.BoxManagerDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BoxDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoxDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoxDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoxDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Accione> Acciones
		{
			get
			{
				return this.GetTable<Accione>();
			}
		}
		
		public System.Data.Linq.Table<Boxeadore> Boxeadores
		{
			get
			{
				return this.GetTable<Boxeadore>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Divisione> Divisiones
		{
			get
			{
				return this.GetTable<Divisione>();
			}
		}
		
		public System.Data.Linq.Table<Municipio> Municipios
		{
			get
			{
				return this.GetTable<Municipio>();
			}
		}
		
		public System.Data.Linq.Table<Registro> Registros
		{
			get
			{
				return this.GetTable<Registro>();
			}
		}
		
		public System.Data.Linq.Table<Torneo> Torneos
		{
			get
			{
				return this.GetTable<Torneo>();
			}
		}
		
		public System.Data.Linq.Table<Pelea> Peleas
		{
			get
			{
				return this.GetTable<Pelea>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.accionesPor2Fechas")]
		public ISingleResult<accionesPor2FechasResult> accionesPor2Fechas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaInicial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaFinal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fechaInicial, fechaFinal);
			return ((ISingleResult<accionesPor2FechasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadores")]
		public ISingleResult<reporteBoxeadoresResult> reporteBoxeadores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<reporteBoxeadoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadoresPorCategoria")]
		public ISingleResult<reporteBoxeadoresPorCategoriaResult> reporteBoxeadoresPorCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> categoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoria);
			return ((ISingleResult<reporteBoxeadoresPorCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadoresPorRama")]
		public ISingleResult<reporteBoxeadoresPorRamaResult> reporteBoxeadoresPorRama([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rama", DbType="VarChar(10)")] string rama)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rama);
			return ((ISingleResult<reporteBoxeadoresPorRamaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadoresPorCategoriaDivision")]
		public ISingleResult<reporteBoxeadoresPorCategoriaDivisionResult> reporteBoxeadoresPorCategoriaDivision([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> categoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> division)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoria, division);
			return ((ISingleResult<reporteBoxeadoresPorCategoriaDivisionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadoresPorCategoriaDivisionMunicipio")]
		public ISingleResult<reporteBoxeadoresPorCategoriaDivisionMunicipioResult> reporteBoxeadoresPorCategoriaDivisionMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> categoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> division, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> municipio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoria, division, municipio);
			return ((ISingleResult<reporteBoxeadoresPorCategoriaDivisionMunicipioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadoresPorCategoriaMunicipio")]
		public ISingleResult<reporteBoxeadoresPorCategoriaMunicipioResult> reporteBoxeadoresPorCategoriaMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> categoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> municipio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoria, municipio);
			return ((ISingleResult<reporteBoxeadoresPorCategoriaMunicipioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadoresPorMunicipio")]
		public ISingleResult<reporteBoxeadoresPorMunicipioResult> reporteBoxeadoresPorMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> municipio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), municipio);
			return ((ISingleResult<reporteBoxeadoresPorMunicipioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reporteBoxeadoresPorRamaMunicipio")]
		public ISingleResult<reporteBoxeadoresPorRamaMunicipioResult> reporteBoxeadoresPorRamaMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rama", DbType="VarChar(10)")] string rama, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> municipio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rama, municipio);
			return ((ISingleResult<reporteBoxeadoresPorRamaMunicipioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ReporteGrafica")]
		public ISingleResult<ReporteGraficaResult> ReporteGrafica()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ReporteGraficaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Acciones")]
	public partial class Accione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Accion;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_AccionChanging(int value);
    partial void OnId_AccionChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public Accione()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Accion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Accion
		{
			get
			{
				return this._Id_Accion;
			}
			set
			{
				if ((this._Id_Accion != value))
				{
					this.OnId_AccionChanging(value);
					this.SendPropertyChanging();
					this._Id_Accion = value;
					this.SendPropertyChanged("Id_Accion");
					this.OnId_AccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boxeadores")]
	public partial class Boxeadore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Boxeador;
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private int _Categoria;
		
		private int _Division;
		
		private int _Municipio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_BoxeadorChanging(int value);
    partial void OnId_BoxeadorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnRamaChanging(string value);
    partial void OnRamaChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    partial void OnCategoriaChanging(int value);
    partial void OnCategoriaChanged();
    partial void OnDivisionChanging(int value);
    partial void OnDivisionChanged();
    partial void OnMunicipioChanging(int value);
    partial void OnMunicipioChanged();
    #endregion
		
		public Boxeadore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Boxeador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Boxeador
		{
			get
			{
				return this._Id_Boxeador;
			}
			set
			{
				if ((this._Id_Boxeador != value))
				{
					this.OnId_BoxeadorChanging(value);
					this.SendPropertyChanging();
					this._Id_Boxeador = value;
					this.SendPropertyChanged("Id_Boxeador");
					this.OnId_BoxeadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this.OnRamaChanging(value);
					this.SendPropertyChanging();
					this._Rama = value;
					this.SendPropertyChanged("Rama");
					this.OnRamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="Int NOT NULL")]
		public int Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="Int NOT NULL")]
		public int Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this.OnDivisionChanging(value);
					this.SendPropertyChanging();
					this._Division = value;
					this.SendPropertyChanged("Division");
					this.OnDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="Int NOT NULL")]
		public int Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this.OnMunicipioChanging(value);
					this.SendPropertyChanging();
					this._Municipio = value;
					this.SendPropertyChanged("Municipio");
					this.OnMunicipioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Categoria;
		
		private string _Nombre;
		
		private string _Rama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CategoriaChanging(int value);
    partial void OnId_CategoriaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnRamaChanging(string value);
    partial void OnRamaChanged();
    #endregion
		
		public Categoria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Categoria
		{
			get
			{
				return this._Id_Categoria;
			}
			set
			{
				if ((this._Id_Categoria != value))
				{
					this.OnId_CategoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_Categoria = value;
					this.SendPropertyChanged("Id_Categoria");
					this.OnId_CategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this.OnRamaChanging(value);
					this.SendPropertyChanging();
					this._Rama = value;
					this.SendPropertyChanged("Rama");
					this.OnRamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Divisiones")]
	public partial class Divisione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Division;
		
		private string _Nombre;
		
		private int _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DivisionChanging(int value);
    partial void OnId_DivisionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCategoriaChanging(int value);
    partial void OnCategoriaChanged();
    #endregion
		
		public Divisione()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Division", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Division
		{
			get
			{
				return this._Id_Division;
			}
			set
			{
				if ((this._Id_Division != value))
				{
					this.OnId_DivisionChanging(value);
					this.SendPropertyChanging();
					this._Id_Division = value;
					this.SendPropertyChanged("Id_Division");
					this.OnId_DivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="Int NOT NULL")]
		public int Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Municipios")]
	public partial class Municipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Municipio;
		
		private string _Nombre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_MunicipioChanging(int value);
    partial void OnId_MunicipioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Municipio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Municipio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Municipio
		{
			get
			{
				return this._Id_Municipio;
			}
			set
			{
				if ((this._Id_Municipio != value))
				{
					this.OnId_MunicipioChanging(value);
					this.SendPropertyChanging();
					this._Id_Municipio = value;
					this.SendPropertyChanged("Id_Municipio");
					this.OnId_MunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registros")]
	public partial class Registro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Registros;
		
		private string _Registro1;
		
		private int _Cantidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_RegistrosChanging(int value);
    partial void OnId_RegistrosChanged();
    partial void OnRegistro1Changing(string value);
    partial void OnRegistro1Changed();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    #endregion
		
		public Registro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Registros", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Registros
		{
			get
			{
				return this._Id_Registros;
			}
			set
			{
				if ((this._Id_Registros != value))
				{
					this.OnId_RegistrosChanging(value);
					this.SendPropertyChanging();
					this._Id_Registros = value;
					this.SendPropertyChanged("Id_Registros");
					this.OnId_RegistrosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Registro", Storage="_Registro1", DbType="NChar(40) NOT NULL", CanBeNull=false)]
		public string Registro1
		{
			get
			{
				return this._Registro1;
			}
			set
			{
				if ((this._Registro1 != value))
				{
					this.OnRegistro1Changing(value);
					this.SendPropertyChanging();
					this._Registro1 = value;
					this.SendPropertyChanged("Registro1");
					this.OnRegistro1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Torneo")]
	public partial class Torneo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Torneo;
		
		private string _Nombre;
		
		private int _Id_Categoria;
		
		private string _Rama;
		
		private int _NumParticipantes;
		
		private System.DateTime _FechaCreacion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TorneoChanging(int value);
    partial void OnId_TorneoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnId_CategoriaChanging(int value);
    partial void OnId_CategoriaChanged();
    partial void OnRamaChanging(string value);
    partial void OnRamaChanged();
    partial void OnNumParticipantesChanging(int value);
    partial void OnNumParticipantesChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public Torneo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Torneo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Torneo
		{
			get
			{
				return this._Id_Torneo;
			}
			set
			{
				if ((this._Id_Torneo != value))
				{
					this.OnId_TorneoChanging(value);
					this.SendPropertyChanging();
					this._Id_Torneo = value;
					this.SendPropertyChanged("Id_Torneo");
					this.OnId_TorneoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Categoria", DbType="Int NOT NULL")]
		public int Id_Categoria
		{
			get
			{
				return this._Id_Categoria;
			}
			set
			{
				if ((this._Id_Categoria != value))
				{
					this.OnId_CategoriaChanging(value);
					this.SendPropertyChanging();
					this._Id_Categoria = value;
					this.SendPropertyChanged("Id_Categoria");
					this.OnId_CategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this.OnRamaChanging(value);
					this.SendPropertyChanging();
					this._Rama = value;
					this.SendPropertyChanged("Rama");
					this.OnRamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumParticipantes", DbType="Int NOT NULL")]
		public int NumParticipantes
		{
			get
			{
				return this._NumParticipantes;
			}
			set
			{
				if ((this._NumParticipantes != value))
				{
					this.OnNumParticipantesChanging(value);
					this.SendPropertyChanging();
					this._NumParticipantes = value;
					this.SendPropertyChanged("NumParticipantes");
					this.OnNumParticipantesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pelea")]
	public partial class Pelea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Pelea;
		
		private int _Id_Boxeador1;
		
		private int _Id_Boxeador2;
		
		private int _Id_Torneo;
		
		private int _Etapa;
		
		private System.Nullable<int> _Ganador;
		
		private System.Nullable<System.DateTime> _Fecha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_PeleaChanging(int value);
    partial void OnId_PeleaChanged();
    partial void OnId_Boxeador1Changing(int value);
    partial void OnId_Boxeador1Changed();
    partial void OnId_Boxeador2Changing(int value);
    partial void OnId_Boxeador2Changed();
    partial void OnId_TorneoChanging(int value);
    partial void OnId_TorneoChanged();
    partial void OnEtapaChanging(int value);
    partial void OnEtapaChanged();
    partial void OnGanadorChanging(System.Nullable<int> value);
    partial void OnGanadorChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public Pelea()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Pelea", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Pelea
		{
			get
			{
				return this._Id_Pelea;
			}
			set
			{
				if ((this._Id_Pelea != value))
				{
					this.OnId_PeleaChanging(value);
					this.SendPropertyChanging();
					this._Id_Pelea = value;
					this.SendPropertyChanged("Id_Pelea");
					this.OnId_PeleaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Boxeador1", DbType="Int NOT NULL")]
		public int Id_Boxeador1
		{
			get
			{
				return this._Id_Boxeador1;
			}
			set
			{
				if ((this._Id_Boxeador1 != value))
				{
					this.OnId_Boxeador1Changing(value);
					this.SendPropertyChanging();
					this._Id_Boxeador1 = value;
					this.SendPropertyChanged("Id_Boxeador1");
					this.OnId_Boxeador1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Boxeador2", DbType="Int NOT NULL")]
		public int Id_Boxeador2
		{
			get
			{
				return this._Id_Boxeador2;
			}
			set
			{
				if ((this._Id_Boxeador2 != value))
				{
					this.OnId_Boxeador2Changing(value);
					this.SendPropertyChanging();
					this._Id_Boxeador2 = value;
					this.SendPropertyChanged("Id_Boxeador2");
					this.OnId_Boxeador2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Torneo", DbType="Int NOT NULL")]
		public int Id_Torneo
		{
			get
			{
				return this._Id_Torneo;
			}
			set
			{
				if ((this._Id_Torneo != value))
				{
					this.OnId_TorneoChanging(value);
					this.SendPropertyChanging();
					this._Id_Torneo = value;
					this.SendPropertyChanged("Id_Torneo");
					this.OnId_TorneoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etapa", DbType="Int NOT NULL")]
		public int Etapa
		{
			get
			{
				return this._Etapa;
			}
			set
			{
				if ((this._Etapa != value))
				{
					this.OnEtapaChanging(value);
					this.SendPropertyChanging();
					this._Etapa = value;
					this.SendPropertyChanged("Etapa");
					this.OnEtapaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ganador", DbType="Int")]
		public System.Nullable<int> Ganador
		{
			get
			{
				return this._Ganador;
			}
			set
			{
				if ((this._Ganador != value))
				{
					this.OnGanadorChanging(value);
					this.SendPropertyChanging();
					this._Ganador = value;
					this.SendPropertyChanged("Ganador");
					this.OnGanadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class accionesPor2FechasResult
	{
		
		private string _Descripción;
		
		private System.DateTime _Fecha;
		
		public accionesPor2FechasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this._Descripción = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresPorCategoriaResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresPorCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresPorRamaResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresPorRamaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresPorCategoriaDivisionResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresPorCategoriaDivisionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresPorCategoriaDivisionMunicipioResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresPorCategoriaDivisionMunicipioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresPorCategoriaMunicipioResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresPorCategoriaMunicipioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresPorMunicipioResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresPorMunicipioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class reporteBoxeadoresPorRamaMunicipioResult
	{
		
		private string _Nombre;
		
		private string _Rama;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Categoria;
		
		private string _Division;
		
		private string _Municipio;
		
		public reporteBoxeadoresPorRamaMunicipioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rama", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Rama
		{
			get
			{
				return this._Rama;
			}
			set
			{
				if ((this._Rama != value))
				{
					this._Rama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
	}
	
	public partial class ReporteGraficaResult
	{
		
		private string _Categoria;
		
		private System.Nullable<int> _Divisiones;
		
		public ReporteGraficaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(80) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Divisiones", DbType="Int")]
		public System.Nullable<int> Divisiones
		{
			get
			{
				return this._Divisiones;
			}
			set
			{
				if ((this._Divisiones != value))
				{
					this._Divisiones = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
